import { gql } from "apollo-boost";

const GET_POST = gql`
  query GetContent($username: String!, $permlink: String!){
        get_content(username: $username, permlink: $permlink) {
          id
          author
          account {
            name
            json_metadata{
              cover_image
              name
              about
              location
              website
              profile_image
            }
          }
          permlink
          category
          parent_author
          parent_permlink
          title
          body
          json_metadata
          last_update
          created
          active
          last_payout
          depth
          children
          net_votes
          abs_rshares
          vote_rshares
          children_abs_rshares
          cashout_time
          max_cashout_time
          total_vote_weight
          reward_weight
          total_payout_value
          curator_payout_value
          author_rewards
          net_votes
          root_author
          root_permlink
          max_accepted_payout
          percent_voilk_dollars
          allow_replies
          allow_replies
          allow_curation_rewards
          beneficiaries
          url
          root_title
          pending_payout_value
          total_pending_payout_value
          active_votes {
            voter
            account{
              coining_shares
              json_metadata{
                profile_image
              }
            }
            weight
            rshares
            percent
            reputation
            time
          }
          replies {
            id
            author
            account {
                name
                json_metadata{
                  cover_image
                  name
                  about
                  location
                  website
                  profile_image
                }
              }
            permlink
            category
            parent_author
            parent_permlink
            title
            body
            json_metadata
            last_update
            created
            active
            last_payout
            depth
            children
            net_votes
            abs_rshares
            vote_rshares
            children_abs_rshares
            cashout_time
            max_cashout_time
            total_vote_weight
            reward_weight
            total_payout_value
            curator_payout_value
            author_rewards
            net_votes
            root_author
            root_permlink
            max_accepted_payout
            percent_voilk_dollars
            allow_replies
            allow_replies
            allow_curation_rewards
            beneficiaries
            url
            root_title
            pending_payout_value
            total_pending_payout_value
            active_votes {
              voter
              weight
              rshares
              percent
              reputation
              time
            }
            replies {
              id
              author
              account {
                name
                json_metadata{
                  cover_image
                  name
                  about
                  location
                  website
                  profile_image
                }
              }
              permlink
              category
              parent_author
              parent_permlink
              title
              body
              json_metadata
              last_update
              created
              active
              last_payout
              depth
              children
              net_votes
              abs_rshares
              vote_rshares
              children_abs_rshares
              cashout_time
              max_cashout_time
              total_vote_weight
              reward_weight
              total_payout_value
              curator_payout_value
              author_rewards
              net_votes
              root_author
              root_permlink
              max_accepted_payout
              percent_voilk_dollars
              allow_replies
              allow_replies
              allow_curation_rewards
              beneficiaries
              url
              root_title
              pending_payout_value
              total_pending_payout_value
              active_votes {
                voter
                weight
                rshares
                percent
                reputation
                time
              }
              replies {
                id
                author
                account {
                    name
                    json_metadata{
                      cover_image
                      name
                      about
                      location
                      website
                      profile_image
                    }
                  }
                permlink
                category
                parent_author
                parent_permlink
                title
                body
                json_metadata
                last_update
                created
                active
                last_payout
                depth
                children
                net_votes
                abs_rshares
                vote_rshares
                children_abs_rshares
                cashout_time
                max_cashout_time
                total_vote_weight
                reward_weight
                total_payout_value
                curator_payout_value
                author_rewards
                net_votes
                root_author
                root_permlink
                max_accepted_payout
                percent_voilk_dollars
                allow_replies
                allow_replies
                allow_curation_rewards
                beneficiaries
                url
                root_title
                pending_payout_value
                total_pending_payout_value
                active_votes {
                  voter
                  weight
                  rshares
                  percent
                  reputation
                  time
                }
                replies {
                  id
                  author
                  account {
                    name
                    json_metadata{
                      cover_image
                      name
                      about
                      location
                      website
                      profile_image
                    }
                  }
                  permlink
                  category
                  parent_author
                  parent_permlink
                  title
                  body
                  json_metadata
                  last_update
                  created
                  active
                  last_payout
                  depth
                  children
                  net_votes
                  abs_rshares
                  vote_rshares
                  children_abs_rshares
                  cashout_time
                  max_cashout_time
                  total_vote_weight
                  reward_weight
                  total_payout_value
                  curator_payout_value
                  author_rewards
                  net_votes
                  root_author
                  root_permlink
                  max_accepted_payout
                  percent_voilk_dollars
                  allow_replies
                  allow_replies
                  allow_curation_rewards
                  beneficiaries
                  url
                  root_title
                  pending_payout_value
                  total_pending_payout_value
                  active_votes {
                    voter
                    weight
                    rshares
                    percent
                    reputation
                    time
                  }
                  replies {
                    id
                    author
                    account {
                        name
                        json_metadata{
                          cover_image
                          name
                          about
                          location
                          website
                          profile_image
                        }
                      }
                    permlink
                    category
                    parent_author
                    parent_permlink
                    title
                    body
                    json_metadata
                    last_update
                    created
                    active
                    last_payout
                    depth
                    children
                    net_votes
                    abs_rshares
                    vote_rshares
                    children_abs_rshares
                    cashout_time
                    max_cashout_time
                    total_vote_weight
                    reward_weight
                    total_payout_value
                    curator_payout_value
                    author_rewards
                    net_votes
                    root_author
                    root_permlink
                    max_accepted_payout
                    percent_voilk_dollars
                    allow_replies
                    allow_replies
                    allow_curation_rewards
                    beneficiaries
                    url
                    root_title
                    pending_payout_value
                    total_pending_payout_value
                    active_votes {
                      voter
                      weight
                      rshares
                      percent
                      reputation
                      time
                    }
                    replies {
                      id
                      author
                      account {
                        name
                        json_metadata{
                          cover_image
                          name
                          about
                          location
                          website
                          profile_image
                        }
                      }
                      permlink
                      category
                      parent_author
                      parent_permlink
                      title
                      body
                      json_metadata
                      last_update
                      created
                      active
                      last_payout
                      depth
                      children
                      net_votes
                      abs_rshares
                      vote_rshares
                      children_abs_rshares
                      cashout_time
                      max_cashout_time
                      total_vote_weight
                      reward_weight
                      total_payout_value
                      curator_payout_value
                      author_rewards
                      net_votes
                      root_author
                      root_permlink
                      max_accepted_payout
                      percent_voilk_dollars
                      allow_replies
                      allow_replies
                      allow_curation_rewards
                      beneficiaries
                      url
                      root_title
                      pending_payout_value
                      total_pending_payout_value
                      active_votes {
                        voter
                        weight
                        rshares
                        percent
                        reputation
                        time
                      }
                      replies {id}
                      author_reputation
                      promoted
                      body_length
                      reblogged_by
                    }
                    author_reputation
                    promoted
                    body_length
                    reblogged_by
                  }
                  author_reputation
                  promoted
                  body_length
                  reblogged_by
                }
                author_reputation
                promoted
                body_length
                reblogged_by
              }
              author_reputation
              promoted
              body_length
              reblogged_by
            }
            author_reputation
            promoted
            body_length
            reblogged_by
          }
          author_reputation
          promoted
          body_length
          reblogged_by
        }
      }
`;

export { GET_POST }

